name: terraform
on:
  push:
    branches:
      - develop
      - 'feature-#**'
    paths:
      - 'projects/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      project_id:
        description: "Project Identifier"
        required: true
      plan_apply_id:
        type: choice
        description: "plan/apply"
        options:
        - plan
        - apply
        required: true
        default: "plan"
      tl_approved_id:
        type: boolean
        description: "TL Approved"
        default: false
      tfstate_uhlock_id:
        type: boolean
        description: "tfstate unlock"
        default: false

jobs:
  get-information:
    runs-on: [self-hosted, linux, x64, gdp_infra_full_access]

    env:
      ENV: "dev"
      SEPARATOR1: "[["
      SEPARATOR2: "]]"
      PROJECTS: "./projects"

    outputs:
      work_dir: ${{ steps.check_project.outputs.work_dir }}
      plan_apply: ${{ steps.check_project.outputs.work_dir }}
      unlock: ${{ steps.check_project.outputs.unlock }}
      project: ${{ steps.check_project.outputs.project }}
      tl_approved: ${{ steps.check_project.outputs.tl_approved }}

    steps:
      - name: Check Project Identifier
        id: check_project
        run:
          mes=$(echo ${{ github.event.head_commit.message }} | awk '{ gsub("","", $0); print)')
          sep1=$(echo ${{ env. SEPARATOR1 }})
          sep2=$(echo ${{ env. SEPARATOR2 }})
          github_event_name=$(echo ${{ github.event_name }})
          input_project_id=$(echo ${{ github.event.inputs.project_id }}) 
          input_plan_apply=$(echo ${{ github.event.inputs.plan_apply_id }})
          input_unlock=$(echo ${{ github.event.inputs.tfstate_unlock_id }})
          input_tl_approved=$(echo ${{ github.event.inputs.tl_approved_id }})
          if [ -n "$input_project_id"] && [ "$github_event_name" == "workflow_dispatch" ]; then
            project_id=$input_project_id
          elif [ -z "$input_project_id"] && [ "$github_event_name" == "push" ]; then
            project_id=$(echo $mes $sep1 $sep2 | awk '{print substr($1, index($1, $2)+length($2), index($1, $3)-index($1, $2)-length($3))}')
            input_plan_apply="plan"
          fi
          if [ -z "$project_id" ]:then
            echo "プロジェクト識別子未設定なので終了します"
            echo "work_dir= __not_difined" >> $GITHUB_OUTPUT
            echo "plan_apply=__not_difined" >> $GITHUB_OUTPUT
          else
           echo
           echo
           echo
           echo
           echo
          fi





          




